#!/bin/bash

get_bool() {
    device_info="$1"
    status="$2"

    val=$(echo "$device_info" | grep "$status:" | awk '{print $2}')
    if [ "$val" = "yes" ]; then
        echo true
    else
        echo false
    fi
}

print_device() {
    mac_address="$1"

    device_info=$(bluetoothctl info "$mac_address")

    name=$(echo "$device_info" | grep "Name:" | awk -F ': ' '{print $2}')
    if [ "$name" = "" ]; then
        return
    fi

    connected=$(get_bool "$device_info" "Connected")
    trusted=$(get_bool "$device_info" "Trusted")
    battery=$(echo "$device_info" | grep "Battery Percentage:" | awk -F '[()]' '{print $2}')

    if ! $first; then
        printf ','
    fi
    first=false

    printf '{'
    printf "\"mac_address\":\"$mac_address\""
    printf ",\"name\":\"$name\""
    printf ",\"connected\":$connected"
    printf ",\"trusted\":$trusted"
    if [ -n "$battery" ]; then
        printf ",\"battery\":$battery"
    fi
    printf '}'
}

printf '['

first=true
devices=$(bluetoothctl devices)
while IFS= read -r line; do
    mac_address=$(echo "$line" | cut -d ' ' -f 2)
    print_device "$mac_address"
done <<< "$devices"

printf ']\n'
