#!/bin/bash

if [ $1 -lt 1 ] || [ $1 -gt 10 ]; then
    exit
fi

active_workspace=$(~/.config/eww/scripts/get_active_workspace)
if [ $1 = $active_workspace ]; then
    exit
fi

cursorpos=$(hyprctl cursorpos | tr -d ',')
hyprctl dispatch workspace $1
hyprctl dispatch movecursor $cursorpos
