#!/bin/bash

if [ $1 -lt 1 ] || [ $1 -gt 4 ]; then
    exit
fi

active_workspace_pair=$(~/.config/eww/scripts/get_active_workspace_pair)
if [ $1 = $active_workspace_pair ]; then
    exit
fi

cursorpos=$(hyprctl cursorpos | tr -d ',')
hyprctl dispatch workspace $(($1*2))
hyprctl dispatch workspace $(($1*2-1))
hyprctl dispatch movecursor $cursorpos
