#!/bin/bash

emit() {
    echo $(~/.config/eww/scripts/get_workspace_ids)
}

emit

socat -u "UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" - |
while read -r line; do
    case ${line%>>*} in
        focusedmon|createworkspace|movewindow|destroyworkspace|monitor*)
            emit
            ;;
    esac
done
