#!/bin/bash

emit() {
    echo $(~/.config/eww/scripts/get_active_workspace_pair)
}

emit

socat -u "UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" - |
while read -r line; do
    case ${line%>>*} in
        focusedmon|createworkspace|movewindow|destroyworkspace|monitor*)
            emit
            ;;
    esac
done
